import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TrojanMarketPlace',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="mytheme">
      {/* <body className="flex flex-col min-h-screen inter">
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body> */}
      <body className={inter.className + " flex flex-col min-h-screen justify-between"}>
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}